create table test_all_types (
i INTEGER,
bt BIT,
ti TINYINT,
si SMALLINT,
bi BIGINT,
dcml DECIMAL,
f FLOAT,
d DOUBLE,
r REAL,
t TIME,
dt DATE,
ts TIMESTAMP,
vc VARCHAR(128),
txt TEXT,
ttxt TINYTEXT,
mtxt MEDIUMTEXT,
ltxt LONGTEXT,
c CHAR,
blb BLOB,
tblb TINYBLOB,
mblb MEDIUMBLOB,
lblb LONGBLOB,
bin BINARY,
vbin VARBINARY(128),
PRIMARY KEY (i) -- required to use update methods of result set
)
